version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:z
  web:
    build: .
    command: bundle exec rails s -p 8000 -b '0.0.0.0'
    volumes:
      - .:/myapp:z
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
