version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-jessie
    steps:
      - checkout
      - run: <command>
  test:
    docker:
      - image: circleci/ruby:2.3-jessie
    steps:
      - checkout
      - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test