version: 2.1
jobs:
  test:
    docker:
       - image: circleci/ruby:2.5.1
         environment:
           RAILS_ENV: test
           PG_HOST: localhost
           PG_USER: postgres
       - image: circleci/postgres:9.5
         environment:
           POSTGRES_USER: postgres
           POSTGRES_DB: kpt_test
           POSTGRES_PASSWORD: ""
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run: sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: RAILS_ENV=test bundle exec rake db:create
      - run: RAILS_ENV=test bundle exec rake db:schema:load
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            RAILS_ENV=test bundle exec rspec --format progress \
            --format RspecJunitFormatter \
            --out /tmp/test-results/rspec.xml \
            --format progress \
            -- \
            $TEST_FILES
      - run:
          name: run seed
          command: bundle exec rails db:seed
      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
  lint:
    docker:
       - image: circleci/ruby:2.5.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: bundle install
      - run:
          name: run lint
          command: bundle exec rubocop
workflows:
  version: 2
  test-and-lint:
    jobs:
      - test
      - lint
